### ISSUE TITLE
Issues with "generate_matrix_elements_cython", MemoryError

### ISSUE THREAD

**Issue by sangzhe** [rokroskar/imnet#6]
HI, I installed the imnet through `pip install imnet` without any problem.

And when I execute the command `imnet-analyze --no-spark benchmark`

It returned errors as followed

```
/home/shilab/.local/bin/imnet-analyze:27: RuntimeWarning: No spark libraries found - make sure SPARK_HOME is set
Proceeding in single-core mode
  warnings.warn('No spark libraries found - make sure SPARK_HOME is set\nProceeding in single-core mode', RuntimeWarning)
INFO:imnet.process_strings:number of strings 100
Doing overflow check
Traceback (most recent call last):
  File "/home/shilab/.local/bin/imnet-analyze", line 206, in <module>
    analyze(obj={})
  File "/home/shilab/.local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/shilab/.local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/shilab/.local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shilab/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shilab/.local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/shilab/.local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shilab/.local/bin/imnet-analyze", line 121, in benchmark
    x = list(mat)
  File "imnet/process_strings_cy.pyx", line 64, in generate_matrix_elements_cython
    ld = distance(my_string,s)
MemoryError
```

If I install the package from the source codes I would encounter the module "process_string_cy" not found problem.

Could you please help solve this issue?

**Comment by rokroskar** [comment]
Hi @sangzhe - to install from source you need to make sure to also have cython and a C compiler. 

The memory error is probably what it says - it ran out of memory - could you rerun the command and monitor it using top?
